# Tensor Initialization

---
## a_tensor_initialization.py

In [26]:
import torch

##### torch.Tensor class & torch.tensor function
> default tensor type of torch.Tensor : float32 <br>
> default tensor type of torch.tensor : int64

#### troch.Tensor

In [27]:
# torch.Tensor 클래스로 텐서를 만드는 코드이다.
# torch.Tensor class
t1 = torch.Tensor([1, 2, 3], device='cpu')
print(t1.dtype)   # >>> torch.float32
print(t1.device)  # >>> cpu
print(t1.requires_grad)  # >>> False
print(t1.size())  # torch.Size([3])
print(t1.shape)   # torch.Size([3])
# 모든 tensor는 device, dtype, shape, required_grad 요소를 가지고 있다.
# 위 결과는 이 요소들을 모두 확인하는 코드이다.

torch.float32
cpu
False
torch.Size([3])
torch.Size([3])


In [28]:
# if you have gpu device
# t1_cuda = t1.to(torch.device('cuda'))
# or you can use shorthand
# t1_cuda = t1.cuda()
t1_cpu = t1.cpu()

- 위의 주석은 텐서의 디바이스를 gpu로 바꾸는 코드다.

##### torch.tensor

In [29]:
# 아래는 torch.tensor 을 이용해 텐서를 만드는 코드이다. 
# torch.tensor function
t2 = torch.tensor([1, 2, 3], device='cpu')
print(t2.dtype)  # >>> torch.int64
print(t2.device)  # >>> cpu
print(t2.requires_grad)  # >>> False
print(t2.size())  # torch.Size([3])
print(t2.shape)  # torch.Size([3])

# if you have gpu device
# t2_cuda = t2.to(torch.device('cuda'))
# or you can use shorthand
# t2_cuda = t2.cuda()
t2_cpu = t2.cpu()

torch.int64
cpu
False
torch.Size([3])
torch.Size([3])


- dtype을 보면 torch.Tensor와 다르게 int64임을 확인할 수 있다.

#### Size & ndims of Tensor

In [30]:
a1 = torch.tensor(1)			     # shape: torch.Size([]), ndims(=rank): 0
print(a1.shape, a1.ndim)

a2 = torch.tensor([1])		  	     # shape: torch.Size([1]), ndims(=rank): 1
print(a2.shape, a2.ndim)

a3 = torch.tensor([1, 2, 3, 4, 5])   # shape: torch.Size([5]), ndims(=rank): 1
print(a3.shape, a3.ndim)

a4 = torch.tensor([[1], [2], [3], [4], [5]])   # shape: torch.Size([5, 1]), ndims(=rank): 2
print(a4.shape, a4.ndim)

torch.Size([]) 0
torch.Size([1]) 1
torch.Size([5]) 1
torch.Size([5, 1]) 2


- 1과 [1]은 다르다. 대괄호 [] 하나가 한 차원이라고 생각하면 된다.
- 따라서 a2과 a3 모두 1차원이다.
> <p style="font-style:italic"> tip . ndim을 세는 법은 연속적으로 [가 나타나는 횟수를 세면 된다. </p> 

- shape은 각 차원의 요소들의 개수이다. 가장 바깥쪽 괄호의 차원부터 적는다.
- a4의 shape은 가장 바깥쪽 [] 안의 요소가 5, 그 다음 [] 안의 요소는 1개 이므로 [5,1]이 된다. 
> <p style="font-style:italic"> tip . shape 찾는 방법은 가장 작게 있는 요소들 부터 수를 세고 반대로 적으면 된다. (안쪽 괄호부터 찾는 것이 더 편할 경우) </p>

In [31]:
a5 = torch.tensor([                 # shape: torch.Size([3, 2]), ndims(=rank): 2
    [1, 2],
    [3, 4],
    [5, 6]
])
print(a5.shape, a5.ndim)

torch.Size([3, 2]) 2


- 위 텐서는 [ [], [], [], ] 으로 이루어져 있으므로 2차원이다.
- 가장 바깥쪽 [] 안의 요소는 3개, 그 다음 [] 안의 요소는 2개 이므로 이 텐서의 shape은 [3,2]이다.

In [32]:
a6 = torch.tensor([                 # shape: torch.Size([3, 2, 1]), ndims(=rank): 3
    [[1], [2]],
    [[3], [4]],
    [[5], [6]]
])
print(a6.shape, a6.ndim)

torch.Size([3, 2, 1]) 3


- 위 텐서는 [ [[] []], [[] []], [[] []], ] 으로 이루어져 있으므로 3차원이다.
- 가장 바깥쪽 [] 안의 요소는 3개, 그 다음 [] 안의 요소는 2개, 그 다음 [] 안의 요소는 1개 이므로 이 텐서의 shape은 [3,2,1]이다.

In [33]:
a7 = torch.tensor([                 # shape: torch.Size([3, 1, 2, 1]), ndims(=rank): 4
    [[[1], [2]]],
    [[[3], [4]]],
    [[[5], [6]]]
])
print(a7.shape, a7.ndim)

torch.Size([3, 1, 2, 1]) 4


- 위 텐서는 연속으로 [가 4번 나오므로 4차원이다. 
- 가장 안쪽 괄호부터 차원의 요소를 세면 1, 2, 1, 3 이다. 따라서 shape 은 [3,1,2,1]이다.

In [34]:
a8 = torch.tensor([                 # shape: torch.Size([3, 1, 2, 3]), ndims(=rank): 4
    [[[1, 2, 3], [2, 3, 4]]],
    [[[3, 1, 1], [4, 4, 5]]],
    [[[5, 6, 2], [6, 3, 1]]]
])
print(a8.shape, a8.ndim)

torch.Size([3, 1, 2, 3]) 4


- 위 텐서는 연속으로 [가 4번 나오므로 4차원이다. 
- 가장 안쪽 괄호부터 차원의 요소를 세면 3, 2, 1, 3 이다. 따라서 shape 은 [3,1,2,3]이다.

In [35]:
a9 = torch.tensor([                 # shape: torch.Size([3, 1, 2, 3, 1]), ndims(=rank): 5
    [[[[1], [2], [3]], [[2], [3], [4]]]],
    [[[[3], [1], [1]], [[4], [4], [5]]]],
    [[[[5], [6], [2]], [[6], [3], [1]]]]
])
print(a9.shape, a9.ndim)

torch.Size([3, 1, 2, 3, 1]) 5


- 위 텐서는 연속으로 [가 5번 나오므로 ndims = 5 다.
- 안쪽 괄호부터 요소를 세면 1,3,2,1,3 이므로 shape은 [3,1,2,3,1]이다.

In [36]:
a10 = torch.tensor([                 # shape: torch.Size([4, 5]), ndims(=rank): 2
    [1, 2, 3, 4, 5],
    [1, 2, 3, 4, 5],
    [1, 2, 3, 4, 5],
    [1, 2, 3, 4, 5],
])
print(a10.shape, a10.ndim)

torch.Size([4, 5]) 2


- 위 텐서는 연속으로 [가 두번 나오므로 ndims=2이다. 
- 안쪽 괄호부터 요소는 5, 4 씩 있으므로 shape 은 [4,5]이다.

In [37]:
# 불균일한 형태의 리스트를 텐서로 입력받으면 에러가 발생한다. 
# torch는 균일한 형태의 리스트만을 생성한다. 
a11 = torch.tensor([                 # ValueError: expected sequence of length 3 at dim 3 (got 2)
    [[[1, 2, 3], [4, 5]]],
    [[[1, 2, 3], [4, 5]]],
    [[[1, 2, 3], [4, 5]]],
    [[[1, 2, 3], [4, 5]]],
])

ValueError: expected sequence of length 3 at dim 3 (got 2)

- 위 텐서를 실행하면 ValueError: expected sequence of length 3 at dim 3 (got 2) 에러가 발생한다. 
- torch는 균일한 현태의 텐서만을 생성할 수 있다. 즉, 리스트안의 리스트 길이가 일정해야한다. 그러나 예시의 리스트는 불규칙한 형태의 다차원 배열이기 때문에 에러가 발생한다. 

---
## b_tensor_initialization_copy.py

- torch.Tensor와 torch.tensor는 항상 주어진 데이터를 복사한다.

In [ ]:
# numpy array 없이 리스트를 생성해서 torch로 텐서를 만들면, 이 텐서는 복사가 된다. 
l1 = [1, 2, 3]
t1 = torch.Tensor(l1)

l2 = [1, 2, 3]
t2 = torch.tensor(l2)

l3 = [1, 2, 3]
t3 = torch.as_tensor(l3)

l1[0] = 100  # 이 코드에서 리스트의 값을 변경하면
l2[0] = 100
l3[0] = 100

print(t1)   # 텐서의 값은 변경되지 않는다. 
print(t2)
print(t3)
# 이는 torch.Tensor와 torch.tensor가 항상 데이터를 복사하기 때문이다. 

In [ ]:
import numpy as np
# 그러나 numpy array를 사용하여 배열을 만들고, 이를 torch.as_tensorO()메소드로 텐서화 시키면 copy를 피할 수 있다. 

In [ ]:
l4 = np.array([1, 2, 3])
t4 = torch.Tensor(l4)

l5 = np.array([1, 2, 3])
t5 = torch.tensor(l5)

l6 = np.array([1, 2, 3])
t6 = torch.as_tensor(l6)

l4[0] = 100 # l4와 l5의 값은 변하지 않으나
l5[0] = 100
l6[0] = 100 # l6의 값은 100으로 변함을 출력값에서 확인할 수 있다. 

print(t4)
print(t5)
print(t6)


---
## c_tensor_initialization_constant_values.py
> 값을 넣어서 텐서를 초기화 하기.

In [ ]:
# import torch
# 위의 a_initialization.py 파트에서 torch를 import 하였으므로 앞으로 임포트 문은 생략한다.

- torch.ones(*size)

In [ ]:
# 사이즈가 (5,)이고, 값이 모두 1인 텐서를 생성
t1 = torch.ones(size=(5,))  # or torch.ones(5): 여기서 size=(5,)를 5로 생략이 가능하다.
# t1과 동일한 차원과 크기이며, 값이 모두 1인 텐서 생성
t1_like = torch.ones_like(input=t1)
print(t1)  # >>> tensor([1., 1., 1., 1., 1.])
print(t1_like)  # >>> tensor([1., 1., 1., 1., 1.])
# 두 텐서의 출력 결과는 같다. 

- torch.zeros

In [ ]:
# 사이즈가 (6,)이고, 값이 모두 0인 텐서를 생성
t2 = torch.zeros(size=(6,))  # or torch.zeros(6)
# t2과 동일한 차원과 크기이며. 값이 모두 0인 텐서 생성
t2_like = torch.zeros_like(input=t2)
print(t2)  # >>> tensor([0., 0., 0., 0., 0., 0.])
print(t2_like)  # >>> tensor([0., 0., 0., 0., 0., 0.])
# 두 텐서의 출력 결과는 같다. 

- torch.empty

In [ ]:
# 사이즈가 (4,)이고, 초기화 되지 않은 값을 넣어서 텐서 생성.
# 그러나 대부분의 값이 0이다. 
t3 = torch.empty(size=(4,))  # or torch.zeros(4)
# t3과 동일한 차원과 크기이며. 초기화 되지 않은 값을 넣어서 생성
t3_like = torch.empty_like(input=t3)
print(t3)  # >>> tensor([0., 0., 0., 0.])
print(t3_like)  # >>> tensor([0., 0., 0., 0.])
# 초기화 되지 않은 값을 넣어 생성하였으므로
# 두 텐서의 출력이 다름을 확인 할 수 있다.

- torch.eye

In [ ]:
# torch.eye(n)은 크기가 n인 단위행렬을 생성하는 메소드다.
t4 = torch.eye(n=3)
print(t4)
# 출력과 같이 대각선 방향으로만 1이고 나머지는 모두 0임을 볼 수 있다.

---
## d_tensor_initialization_random_values.py
> random 값을 넣어서 텐서 초기화 하기

- torch.randint(low=0, high, size, ...)

In [ ]:
# low와 high 사이의 정수 값들을 균일하게 생성한다. - integer uniform 
t1 = torch.randint(low=10, high=20, size=(1, 2))
print(t1)

- torch.rand(*size,...)

In [ ]:
# 0과 1사이의 uniform distribution로 부터 float 값을 생성한다. 
t2 = torch.rand(size=(1, 3))
print(t2)

- torch.randn(*size,...)

In [ ]:
# 0과 1 사이의 표준 정규 분포도(standard normal distribution)로 부터 랜덤한 float 값을 생성한다. 
t3 = torch.randn(size=(1, 3))
print(t3)

- torch.normal(mean, std, size, ...)

In [ ]:
# 매개변수로 주어진 mean과 std, size를 갖는 정규 분포도로 부터 랜덤한 값을 생성한다. 
t4 = torch.normal(mean=10.0, std=1.0, size=(3, 2))
print(t4)

- torch.linspace(start,end,steps, ...)

In [ ]:
# start 부터 end 까지, 개수는 3인 동일한 간격의 1차원 텐서를 생성한다. 
t5 = torch.linspace(start=0.0, end=5.0, steps=3)
print(t5)
# 0부터 5까지 3개의 값이어야 하므로
# 0, 2.5, 5를 반환한다. 

- torch.arange(start=0, end, step=1, ...)

In [ ]:
# start 부터 end-1 까지 간격이 1인 1차원 텐서를 생성한다.  
t6 = torch.arange(5)
print(t6)
# 4까지만 출력됨을 볼 수 있다.

- torch.manual_seed(value)

In [ ]:
# 난수생성기의 시드값에 고정된 값을 넣어서 생성하면, 같은 값을 다시 생성할 수 있다.
torch.manual_seed(1729) # 시드값으로 1729를 준다. 
random1 = torch.rand(2, 3)
print(random1)

random2 = torch.rand(2, 3)
print(random2)
# 두 텐서의 값을 다르게 나온다.
print()

torch.manual_seed(1729) # 다시 시드를 주고
random3 = torch.rand(2, 3) # 텐서를 생성하면, 위의 텐서와 같은 텐서가 출력된다. 
print(random3)

random4 = torch.rand(2, 3)
print(random4)


---
---
# Tensor Operations
---
---
## e_tensor_type_conversion.py
> 텐서의 형변환

In [ ]:
a = torch.ones((2, 3)) # 1으로 채워진 텐서 생성
print(a.dtype)  # torch.ones 로 텐서를 생성하면 default dtype은 float32이다.

b = torch.ones((2, 3), dtype=torch.int16) # 텐서를 생성할 때 dtype을 지정할 수 있다.
print(b) # 출력할 때, dtype도 같이 출력됨

c = torch.rand((2, 3), dtype=torch.float64) * 20. # -> broadcasting 
print(c) # broadcasting을 해도 dtype은 똑같다.

d =c.to(torch.int32) # 텐서 c의 dtype을 int32로 바꾼다.
print(d)

In [38]:
# 인자로 dtype 값을 주어서 형식을 지정할 수 있다.
double_d = torch.ones(10, 2, dtype=torch.double)
short_e = torch.tensor([[1, 2]], dtype=torch.short)
# 메소드로 형식을 지정할 수 있다.
double_d = torch.zeros(10, 2).double()
short_e = torch.ones(10, 2).short()

# .to(dtype) 으로 형식을 바꿀 수 있다.
double_d = torch.zeros(10, 2).to(torch.double)
short_e = torch.ones(10, 2).to(dtype=torch.short)

double_d = torch.zeros(10, 2).type(torch.double)
short_e = torch.ones(10, 2). type(dtype=torch.short)

print(double_d.dtype)
print(short_e.dtype)

torch.float64
torch.int16
torch.float64


In [40]:
# double 타입으로 생성한 텐서를 short 타입으로 바꾸는 코드
double_f = torch.rand(5, dtype=torch.double)
short_g = double_f.to(torch.short)
print((double_f * short_g).dtype) 
# double type * short type => double type

torch.float64


---
## f_tensor_operations.py
> 텐서의 기본 연산

In [41]:
t1 = torch.ones(size=(2, 3))
t2 = torch.ones(size=(2, 3))
# 1로 채워진 size가 (2,3)인 텐서 두개 생성

In [42]:
# 두 텐서의 합
t3 = torch.add(t1, t2) # add 메소드
t4 = t1 + t2           # + 연산자
print(t3)
print(t4)
# 결과가 같다.

tensor([[2., 2., 2.],
        [2., 2., 2.]])
tensor([[2., 2., 2.],
        [2., 2., 2.]])


In [43]:
# 두 텐서의 차
t5 = torch.sub(t1, t2) # sub 메소드
t6 = t1 - t2           # - 연산자
print(t5)
print(t6)
# 결과가 같다.

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [44]:
# 두 텐서의 곱
t7 = torch.mul(t1, t2) # mul 메소드
t8 = t1 * t2           # * 연산자
print(t7)
print(t8)
# 결과가 같다.

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [45]:
# 두 텐서의 나눗셈
t9 = torch.div(t1, t2) # div 메소드   
t10 = t1 / t2          # / 연산자
print(t9)
print(t10)
# 결과가 같다.

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


---
## g_tensor_operations_mm.py
> 텐서의 행렬 곱1

In [46]:
# 두 1차원 텐서의 dot product(내적)
t1 = torch.dot(
  torch.tensor([2, 3]), torch.tensor([2, 1])
)
print(t1, t1.size())
# 2*2 + 3*1 = 7 이므로 t1은 7이 출력된다.

tensor(7) torch.Size([])


In [47]:
# broadcasting 없이 2차원 텐서의 행렬곱 연산.
# nxm 행렬과 mxp 행렬이 곱해지면 nxp 행렬을 반환한다. 
t2 = torch.randn(2, 3)
t3 = torch.randn(3, 2)
t4 = torch.mm(t2, t3)
print(t4, t4.size())
# 따라서 t4의 Size는 [2,2]

tensor([[-3.5670, -3.2592],
        [-1.3736, -1.2643]]) torch.Size([2, 2])


In [48]:
# broadcasting없이 batch 행렬의 곱연산
# bxnxm 행렬과 bxmxp 행렬이 곱해지면 bxnxp 행렬을 반환한다. 
t5 = torch.randn(10, 3, 4) # 3차원 행렬
t6 = torch.randn(10, 4, 5)
t7 = torch.bmm(t5, t6)
print(t7.size())
# size는 [10, 3, 5]이다.

torch.Size([10, 3, 5])


---
## h_tensor_operations_matmul.py
> 텐서의 행렬곱2

In [ ]:
# broadcasting을 포함한 행렬곱 연산자.

# 1차원 텐서는 dot product를 한다. 
# vector x vector: dot product 
t1 = torch.randn(3)
t2 = torch.randn(3)
print(torch.matmul(t1, t2).size())  # torch.Size([])

# 2차원 텐서와 1차원 텐서의 행렬곱은 broadcasting이다.
-- 여기서 부터 내용좀 검색해야할듯!!!
# matrix x vector: broadcasted dot
t3 = torch.randn(3, 4)
t4 = torch.randn(4)
print(torch.matmul(t3, t4).size())  # torch.Size([3])

# batched matrix x vector: broadcasted dot
t5 = torch.randn(10, 3, 4)
t6 = torch.randn(4)
print(torch.matmul(t5, t6).size())  # torch.Size([10, 3])

# batched matrix x batched matrix: bmm
t7 = torch.randn(10, 3, 4)
t8 = torch.randn(10, 4, 5)
print(torch.matmul(t7, t8).size())  # torch.Size([10, 3, 5])

# batched matrix x matrix: bmm
t9 = torch.randn(10, 3, 4)
t10 = torch.randn(4, 5)
print(torch.matmul(t9, t10).size())  # torch.Size([10, 3, 5])


---
## i_tensor_broadcasting.py

In [ ]:
import torch

t1 = torch.tensor([1.0, 2.0, 3.0])
t2 = 2.0
print(t1 * t2)

print("#" * 50, 1)

t3 = torch.tensor([[0, 1], [2, 4], [10, 10]])
t4 = torch.tensor([4, 5])
print(t3 - t4)

print("#" * 50, 2)

t5 = torch.tensor([[1., 2.], [3., 4.]])
print(t5 + 2.0)  # t5.add(2.0)
print(t5 - 2.0)  # t5.sub(2.0)
print(t5 * 2.0)  # t5.mul(2.0)
print(t5 / 2.0)  # t5.div(2.0)

print("#" * 50, 3)


def normalize(x):
  return x / 255


t6 = torch.randn(3, 28, 28)
print(normalize(t6).size())

print("#" * 50, 4)

t7 = torch.tensor([[1, 2], [0, 3]])  # torch.Size([2, 2])
t8 = torch.tensor([[3, 1]])  # torch.Size([1, 2])
t9 = torch.tensor([[5], [2]])  # torch.Size([2, 1])
t10 = torch.tensor([7])  # torch.Size([1])
print(t7 + t8)   # >>> tensor([[4, 3], [3, 4]])
print(t7 + t9)   # >>> tensor([[6, 7], [2, 5]])
print(t8 + t9)   # >>> tensor([[8, 6], [5, 3]])
print(t7 + t10)  # >>> tensor([[ 8, 9], [ 7, 10]])

print("#" * 50, 5)

t11 = torch.ones(4, 3, 2)
t12 = t11 * torch.rand(3, 2)  # 3rd & 2nd dims identical to t11, dim 0 absent
print(t12.shape)

t13 = torch.ones(4, 3, 2)
t14 = t13 * torch.rand(3, 1)  # 3rd dim = 1, 2nd dim is identical to t13
print(t14.shape)

t15 = torch.ones(4, 3, 2)
t16 = t15 * torch.rand(1, 2)  # 3rd dim is identical to t15, 2nd dim is 1
print(t16.shape)

t17 = torch.ones(5, 3, 4, 1)
t18 = torch.rand(3, 1, 1)  # 2nd dim is identical to t17, 3rd and 4th dims are 1
print((t17 + t18).size())

print("#" * 50, 6)

t19 = torch.empty(5, 1, 4, 1)
t20 = torch.empty(3, 1, 1)
print((t19 + t20).size())  # torch.Size([5, 3, 4, 1])

t21 = torch.empty(1)
t22 = torch.empty(3, 1, 7)
print((t21 + t22).size())  # torch.Size([3, 1, 7])

t23 = torch.ones(3, 3, 3)
t24 = torch.ones(3, 1, 3)
print((t23 + t24).size())  # torch.Size([3, 3, 3])

# t25 = torch.empty(5, 2, 4, 1)
# t26 = torch.empty(3, 1, 1)
# print((t25 + t26).size())
# RuntimeError: The size of tensor a (2) must match
# the size of tensor b (3) at non-singleton dimension 1

print("#" * 50, 7)

t27 = torch.ones(4) * 5
print(t27)  # >>> tensor([ 5, 5, 5, 5])

t28 = torch.pow(t27, 2)
print(t28)  # >>> tensor([ 25, 25, 25, 25])

exp = torch.arange(1., 5.)  # tensor([ 1.,  2.,  3.,  4.])
a = torch.arange(1., 5.)  # tensor([ 1.,  2.,  3.,  4.])
t29 = torch.pow(a, exp)
print(t29)  # >>> tensor([   1.,    4.,   27.,  256.])


---
## j_tensor_indexing_slicing.py

In [ ]:
import torch

x = torch.tensor(
  [[0, 1, 2, 3, 4],
   [5, 6, 7, 8, 9],
   [10, 11, 12, 13, 14]]
)

print(x[1])  # >>> tensor([5, 6, 7, 8, 9])
print(x[:, 1])  # >>> tensor([1, 6, 11])
print(x[1, 2])  # >>> tensor(7)
print(x[:, -1])  # >>> tensor([4, 9, 14)

print("#" * 50, 1)

print(x[1:])  # >>> tensor([[ 5,  6,  7,  8,  9], [10, 11, 12, 13, 14]])
print(x[1:, 3:])  # >>> tensor([[ 8,  9], [13, 14]])

print("#" * 50, 2)

y = torch.zeros((6, 6))
y[1:4, 2] = 1
print(y)

print(y[1:4, 1:4])

print("#" * 50, 3)

z = torch.tensor(
  [[1, 2, 3, 4],
   [2, 3, 4, 5],
   [5, 6, 7, 8]]
)
print(z[:2])
print(z[1:, 1:3])
print(z[:, 1:])

z[1:, 1:3] = 0
print(z)


---
## k_tensor_reshaping.py

In [ ]:
import torch

t1 = torch.tensor([[1, 2, 3], [4, 5, 6]])
t2 = t1.view(3, 2)  # Shape becomes (3, 2)
t3 = t1.reshape(1, 6)  # Shape becomes (1, 6)
print(t2)
print(t3)

t4 = torch.arange(8).view(2, 4)  # Shape becomes (2, 4)
t5 = torch.arange(6).view(2, 3)  # Shape becomes (2, 3)
print(t4)
print(t5)

print("#" * 50, 1)

# Original tensor with shape (1, 3, 1)
t6 = torch.tensor([[[1], [2], [3]]])

# Remove all dimensions of size 1
t7 = t6.squeeze()  # Shape becomes (3,)

# Remove dimension at position 0
t8 = t6.squeeze(0)  # Shape becomes (3, 1)
print(t7)
print(t8)

print("#" * 50, 2)

# Original tensor with shape (3,)
t9 = torch.tensor([1, 2, 3])

# Add a new dimension at position 1
t10 = t9.unsqueeze(1)  # Shape becomes (3, 1)
print(t10)

t11 = torch.tensor(
  [[1, 2, 3],
   [4, 5, 6]]
)
t12 = t11.unsqueeze(1)  # Shape becomes (2, 1, 3)
print(t12, t12.shape)

print("#" * 50, 3)

# Original tensor with shape (2, 3)
t13 = torch.tensor([[1, 2, 3], [4, 5, 6]])

# Flatten the tensor
t14 = t13.flatten()  # Shape becomes (6,)

print(t14)

# Original tensor with shape (2, 2, 2)
t15 = torch.tensor([[[1, 2],
                     [3, 4]],
                    [[5, 6],
                     [7, 8]]])
t16 = torch.flatten(t15)

t17 = torch.flatten(t15, start_dim=1)

print(t16)
print(t17)

print("#" * 50, 4)

t18 = torch.randn(2, 3, 5)
print(t18.shape)  # >>> torch.Size([2, 3, 5])
print(torch.permute(t18, (2, 0, 1)).size())  # >>> torch.Size([5, 2, 3])

# Original tensor with shape (2, 3)
t19 = torch.tensor([[1, 2, 3], [4, 5, 6]])

# Permute the dimensions
t20 = torch.permute(t19, dims=(0, 1))  # Shape becomes (2, 3) still
t21 = torch.permute(t19, dims=(1, 0))  # Shape becomes (3, 2)
print(t20)
print(t21)

# Transpose the tensor
t22 = torch.transpose(t19, 0, 1)  # Shape becomes (3, 2)

print(t22)

t23 = torch.t(t19)  # Shape becomes (3, 2)

print(t23)


---
## l_tensor_concat.py

In [ ]:
import torch

t1 = torch.zeros([2, 1, 3])
t2 = torch.zeros([2, 3, 3])
t3 = torch.zeros([2, 2, 3])

t4 = torch.cat([t1, t2, t3], dim=1)
print(t4.shape)

print("#" * 50, 1)

t5 = torch.arange(0, 3)  # tensor([0, 1, 2])
t6 = torch.arange(3, 8)  # tensor([3, 4, 5, 6, 7])

t7 = torch.cat((t5, t6), dim=0)
print(t7.shape)  # >>> torch.Size([8])
print(t7)  # >>> tensor([0, 1, 2, 3, 4, 5, 6, 7])

print("#" * 50, 2)

t8 = torch.arange(0, 6).reshape(2, 3)  # torch.Size([2, 3])
t9 = torch.arange(6, 12).reshape(2, 3)  # torch.Size([2, 3])

# 2차원 텐서간 병합
t10 = torch.cat((t8, t9), dim=0)
print(t10.size())  # >>> torch.Size([4, 3])
print(t10)
# >>> tensor([[ 0,  1,  2],
#             [ 3,  4,  5],
#             [ 6,  7,  8],
#             [ 9, 10, 11]])

t11 = torch.cat((t8, t9), dim=1)
print(t11.size())  # >>>torch.Size([2, 6])
print(t11)
# >>> tensor([[ 0,  1,  2,  6,  7,  8],
#             [ 3,  4,  5,  9, 10, 11]])

print("#" * 50, 3)

t12 = torch.arange(0, 6).reshape(2, 3)  # torch.Size([2, 3])
t13 = torch.arange(6, 12).reshape(2, 3)  # torch.Size([2, 3])
t14 = torch.arange(12, 18).reshape(2, 3)  # torch.Size([2, 3])

t15 = torch.cat((t12, t13, t14), dim=0)
print(t15.size())  # >>> torch.Size([6, 3])
print(t15)
# >>> tensor([[ 0,  1,  2],
#             [ 3,  4,  5],
#             [ 6,  7,  8],
#             [ 9, 10, 11],
#             [12, 13, 14],
#             [15, 16, 17]])

t16 = torch.cat((t12, t13, t14), dim=1)
print(t16.size())  # >>> torch.Size([2, 9])
print(t16)
# >>> tensor([[ 0,  1,  2,  6,  7,  8, 12, 13, 14],
#             [ 3,  4,  5,  9, 10, 11, 15, 16, 17]])

print("#" * 50, 4)

t17 = torch.arange(0, 6).reshape(1, 2, 3)  # torch.Size([1, 2, 3])
t18 = torch.arange(6, 12).reshape(1, 2, 3)  # torch.Size([1, 2, 3])

t19 = torch.cat((t17, t18), dim=0)
print(t19.size())  # >>> torch.Size([2, 2, 3])
print(t19)
# >>> tensor([[[ 0,  1,  2],
#              [ 3,  4,  5]],
#             [[ 6,  7,  8],
#              [ 9, 10, 11]]])

t20 = torch.cat((t17, t18), dim=1)
print(t20.size())  # >>> torch.Size([1, 4, 3])
print(t20)
# >>> tensor([[[ 0,  1,  2],
#              [ 3,  4,  5],
#              [ 6,  7,  8],
#              [ 9, 10, 11]]])

t21 = torch.cat((t17, t18), dim=2)
print(t21.size())  # >>> torch.Size([1, 2, 6])
print(t21)
# >>> tensor([[[ 0,  1,  2,  6,  7,  8],
#              [ 3,  4,  5,  9, 10, 11]]])


---
## m_tensor_stacking.py

In [ ]:
import torch

t1 = torch.tensor([[1, 2, 3], [4, 5, 6]])
t2 = torch.tensor([[7, 8, 9], [10, 11, 12]])

t3 = torch.stack([t1, t2], dim=0)
t4 = torch.cat([t1.unsqueeze(dim=0), t2.unsqueeze(dim=0)], dim=0)
print(t3.shape, t3.equal(t4))

t5 = torch.stack([t1, t2], dim=1)
t6 = torch.cat([t1.unsqueeze(dim=1), t2.unsqueeze(dim=1)], dim=1)
print(t5.shape, t5.equal(t6))

t7 = torch.stack([t1, t2], dim=2)
t8 = torch.cat([t1.unsqueeze(dim=2), t2.unsqueeze(dim=2)], dim=2)
print(t7.shape, t7.equal(t8))

print("#" * 50, 1)

t9 = torch.arange(0, 3)  # tensor([0, 1, 2])
t10 = torch.arange(3, 6)  # tensor([3, 4, 5])

print(t9.size(), t10.size())
# >>> torch.Size([3]) torch.Size([3])

t11 = torch.stack((t9, t10), dim=0)
print(t11.size())  # >>> torch.Size([2,3])
print(t11)
# >>> tensor([[0, 1, 2],
#             [3, 4, 5]])

t12 = torch.cat((t9.unsqueeze(0), t10.unsqueeze(0)), dim=0)
print(t11.equal(t12))
# >>> True

t13 = torch.stack((t9, t10), dim=1)
print(t13.size())  # >>> torch.Size([3,2])
print(t13)
# >>> tensor([[0, 3],
#             [1, 4],
#             [2, 5]])
t14 = torch.cat((t9.unsqueeze(1), t10.unsqueeze(1)), dim=1)
print(t13.equal(t14))
# >>> True


---
## n_tensor_vstack_hstack.py

In [ ]:
import torch

t1 = torch.tensor([1, 2, 3])
t2 = torch.tensor([4, 5, 6])
t3 = torch.vstack((t1, t2))
print(t3)
# >>> tensor([[1, 2, 3],
#             [4, 5, 6]])

t4 = torch.tensor([[1], [2], [3]])
t5 = torch.tensor([[4], [5], [6]])
t6 = torch.vstack((t4, t5))
# >>> tensor([[1],
#             [2],
#             [3],
#             [4],
#             [5],
#             [6]])

t7 = torch.tensor([
  [[1, 2, 3], [4, 5, 6]],
  [[7, 8, 9], [10, 11, 12]]
])
print(t7.shape)
# >>> (2, 2, 3)

t8 = torch.tensor([
  [[13, 14, 15], [16, 17, 18]],
  [[19, 20, 21], [22, 23, 24]]
])
print(t8.shape)
# >>> (2, 2, 3)

t9 = torch.vstack([t7, t8])
print(t9.shape)
# >>> (4, 2, 3)

print(t9)
# >>> tensor([[[ 1,  2,  3],
#              [ 4,  5,  6]],
#             [[ 7,  8,  9],
#              [10, 11, 12]],
#             [[13, 14, 15],
#              [16, 17, 18]],
#             [[19, 20, 21],
#              [22, 23, 24]]])

print("#" * 50, 1)

t10 = torch.tensor([1, 2, 3])
t11 = torch.tensor([4, 5, 6])
t12 = torch.hstack((t10, t11))
print(t12)
# >>> tensor([1, 2, 3, 4, 5, 6])

t13 = torch.tensor([[1], [2], [3]])
t14 = torch.tensor([[4], [5], [6]])
t15 = torch.hstack((t13, t14))
print(t15)
# >>> tensor([[1, 4],
#             [2, 5],
#             [3, 6]])

t16 = torch.tensor([
  [[1, 2, 3], [4, 5, 6]],
  [[7, 8, 9], [10, 11, 12]]
])
print(t16.shape)
# >>> (2, 2, 3)

t17 = torch.tensor([
  [[13, 14, 15], [16, 17, 18]],
  [[19, 20, 21], [22, 23, 24]]
])
print(t17.shape)
# >>> (2, 2, 3)

t18 = torch.hstack([t16, t17])
print(t18.shape)
# >>> (2, 4, 3)

print(t18)
# >>> tensor([[[ 1,  2,  3],
#              [ 4,  5,  6],
#              [13, 14, 15],
#              [16, 17, 18]],
#             [[ 7,  8,  9],
#              [10, 11, 12],
#              [19, 20, 21],
#              [22, 23, 24]]])


---
## 고찰 

---
## 숙제 후기